logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

frontend:
  origin: ${FRONTEND_DOMAIN}

cookie:
  domain: ".jaeyoung.store"
  same-site: "None"
  secure: true
  http-only: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

jwt:
  key: ${JWT_SECRET_KEY}
  # 60000 = 1000 * 60 = 1 minutes
  # 300000 = 1000 * 60 * 5 = 5 minutes
  # 3600000 = 1000 * 60 * 60 = 1 hour
  # 2592000000 = 1000 * 60 * 60 * 24 * 30 = 30 days
  access-token-expire-millis: 60000
  refresh-token-expire-millis: 2592000000

kafka:
  topic:
    prefix: ""

spring:
  application:
    name: planet-backend

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${BACKEND_DOMAIN}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
